### ISSUE TITLE
master/developブランチにプロテクションルールを適用する

### ISSUE THREAD

**Issue by turara** [app-dojo-salon/GoodFirstIssue-Practice#7]
"Settings > Branches > Branch protection rules > Add rule" からブランチにルールを設定することができます。

"Require pull request reviews before merging" にチェックを入れると、PRからしか更新できないようにすることができます。
（localのmasterに誤ってコミットしてしまっても、pushできなくなる）

**Comment by aphananthe42** [comment]
<img width="1440" alt="スクリーンショット 2020-08-30 14 59 21" src="https://user-images.githubusercontent.com/68156481/91652363-804fcf80-ead1-11ea-944d-cc115bec51bb.png">
approveする人数とその他の設定はどういたしましょうか？

**Comment by turara** [comment]
2人くらいがいいかもしれないですね。

**Comment by aphananthe42** [comment]
そうですね。
Branch name patternはfeature/で大丈夫でしょうか。

**Comment by turara** [comment]
そこは、たしかmasterとかdevelopを入れるところだった気がします！
（feature/のブランチをプロテクトしたい場合は入れても問題ありません）

**Comment by aphananthe42** [comment]
なるほど 勘違いしてました。
developとmasterに保護をつけました。
デフォルトブランチもmasterではなくdevelopの方がいいと思うのですがいかがでしょうか？
<img width="1440" alt="スクリーンショット 2020-08-30 19 09 08" src="https://user-images.githubusercontent.com/68156481/91656531-58be2e80-eaf4-11ea-8fb4-dba8e500c68c.png">

**Comment by minmin0530** [comment]
デフォルトブランチはdevelopの方がいいと思います！

**Comment by aphananthe42** [comment]
了解です。
デフォルトブランチをdevelopにしました！

**Comment by aphananthe42** [comment]
このissueは閉じちゃっていいですかね

**Comment by minmin0530** [comment]
master/developブランチはプロテクションしてますし、デフォルトブランチはdevelopにしたので、閉じていいと思います。

**Comment by aphananthe42** [comment]
了解です。閉じます。
